<a href="https://colab.research.google.com/github/juliansma/NLP/blob/main/Cuaderno%20de%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Cuaderno de Numpy**


In [2]:
import numpy as np

In [ ]:
a = np.array(13) # dimensión 0
b=np.array([1,2,3,4]) #array de dimensión 1
c=np.array([[1,2,3,4],[5,6,7,8]]) #array de dimensión 2
d=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]]) #array de dimensión 3

print("a =",a,"\n")
print("b =",b,"\n")
print("c =",c,"\n")
print("d =",d,"\n")

a = 13 

b = [1 2 3 4] 

c = [[1 2 3 4]
 [5 6 7 8]] 

d = [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 



In [ ]:
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


#### Indexación básica

In [ ]:
print("a =",a)
print("b[2] = ",b[2]) # elemento con índice 2 (empieza en 0)
print("c[1] =",c[1]) # primer bloque de elementos []
print("d[1] =",d[1]) # primera matriz de elementos

a = 13
b[2] =  3
c[1] = [5 6 7 8]
d[1] = [[ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
print("a =",a)
print("b[2] =",b[2])
print("c[1,2] =",c[1,2]) # del primer bloque el elemento con índice 2 
print("d[1,0,2] =",d[1,0,2]) # de la matríz con índice 1, el bloque de elementos con índice 0, el elemento con índice 2

a = 13
b[2] = 3
c[1,2] = 7
d[1,0,2] = 11


In [ ]:
# SEGMENTAR ARRAYS COMO EN LISTAS 

print(b[1:4]) #b = [1 2 3 4] 
print(c[1,1:3]) #c = [[1 2 3 4][5 6 7 8]] 

[2 3 4]
[6 7]


#### Diferentes tipos de datos en los arrays


In [1]:
verduras = np.array(['Zanahoria','Tomate','Cebolla']) #cadenas
print(verduras.dtype)

NameError: ignored

In [ ]:
# Se puede pasar de número a string pero no al revés 
number_to_string=np.array([6,1,2,4,623,8], dtype='S') #b denota un string
print(number_to_string.dtype)
print(number_to_string)

|S3
[b'6' b'1' b'2' b'4' b'623' b'8']


In [ ]:
try:
    error_array = np.array(['a', '2', '3'], dtype='i') # no tiene sentido que "a" sea entero
except:
    print("hay un error en su lógica")

hay un error en su lógica


In [ ]:
try:
    no_error_array = np.array(['2', '3'], dtype='i') 
except:
    print("hay un error en su lógica")

print(no_error_array)    

[2 3]


#### Forma de los arrays
Número de elementos de la dimensión

In [ ]:
print(a.shape) # a = 13 
print(b.shape) # b = [1 2 3 4] 
print(c.shape) # c = [[1 2 3 4][5 6 7 8]] 
print(d.shape) # d = [[[ 1  2  3  4][ 5  6  7  8]] [[ 9 10 11 12][13 14 15 16]]] 

()
(4,)
(2, 4)
(2, 2, 4)


Podemos cambiar el número de dimensiones o cambair cuántos elementos hay por dimensión (forma).

In [ ]:
# OBJETO.RESHAPE()

print("c =",c,"\n") # 4 elementos x 2 dimensiones
c_1D=c.reshape(1,8)
print("c_1D =",c_1D,"\n") # 8 elementos x 1 dimensión
c_4D=c.reshape(4,2)
print("c_4D =",c_4D,"\n") # 2 elementos x 4 dimensiones

c = [[1 2 3 4]
 [5 6 7 8]] 

c_1D = [[1 2 3 4 5 6 7 8]] 

c_4D = [[1 2]
 [3 4]
 [5 6]
 [7 8]] 



In [ ]:
# Como d tiene 16 elementos, se tiene que re ordenar de tal manera que tenga 16 elementos (2 dim 8 elementos x c/u; 4 dim 4 elementos x c/u; 8 dim 2 elementos x c/u)
try:
    d.reshape(3,5)
except:
    print('Hay un error en sus operaciones')

Hay un error en sus operaciones


In [ ]:
d.reshape(2,2,2,2)

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

#### Dimensión desconocida

In [3]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr.reshape(3,-1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# APLANAR CUALQUIER ARRAY A UNA DIMENSIÓN

arr.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Transpuesta

In [ ]:
# OBJETO.T

print("c =",c,"\n")
print("c.T =",c.T)

c = [[1 2 3 4]
 [5 6 7 8]] 

c.T = [[1 5]
 [2 6]
 [3 7]
 [4 8]]


#### Iterar Arrays

In [ ]:
print("d=",d,"\n")

d= [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 



In [ ]:
for x in d:
    print(x)

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# Se necesita un for para cada dimensión 
for x in d:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [ ]:
# mditer --> haer la anterior iteración de una forma más óptima
for x in np.nditer(d):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


## *Operaciones entre arrays*

#### Suma

*   np.add --> entre argumentos de dos arrays (con la misma forma)
*   np.sum --> hace la suma de n elementos


In [ ]:
arr1=np.array([[1,2,3],
               [4,5,6]])
arr2=np.array([[6,5,4],
               [3,2,1]])
print(np.add(arr1,arr2))
np.sum(arr1)

[[7 7 7]
 [7 7 7]]


21

In [ ]:
arr3=np.array([[1,1,1],[1,1,1]])
print(np.sum([arr1,arr2]))
print(np.sum([arr1,arr2,arr3]))

42
48


np.sum en el eje 0 aplica lo mismo que np.add

In [ ]:
np.sum([arr1,arr2, arr3],axis=0)

array([[8, 8, 8],
       [8, 8, 8]])

In [ ]:
np.sum([arr1,arr2, arr3],axis=1)

array([[5, 7, 9],
       [9, 7, 5],
       [2, 2, 2]])

#### Multiplicación
np.prod es similar a np.sum

In [ ]:
print("arr1=\n",arr1,"\n")
print("arr2=\n",arr2,"\n")
print(np.prod([arr1,arr2]),"\n")
print(np.prod([arr1,arr2],axis=0),"\n")
print(np.prod([arr1,arr2],axis=1))

arr1=
 [[1 2 3]
 [4 5 6]] 

arr2=
 [[6 5 4]
 [3 2 1]] 

518400 

[[ 6 10 12]
 [12 10  6]] 

[[ 4 10 18]
 [18 10  4]]


#### Multiplicación matricial

In [ ]:
np.matmul(arr1, arr2.T) # Multiplicación de matrices normal

array([[28, 10],
       [73, 28]])

In [ ]:
np.dot(arr1, arr2.T) # Multiplicación de matrices normal (solo para dim 2)

array([[28, 10],
       [73, 28]])

In [ ]:
print("d =\n",d,"\n") #2,2,4
print("d.reshape =\n",d.reshape(2,4,2),"\n") #2,4,2
np.dot(d,d.reshape(2,4,2)) #2,2,2,2

d =
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

d.reshape =
 [[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]] 



array([[[[ 50,  60],
         [130, 140]],

        [[114, 140],
         [322, 348]]],


       [[[178, 220],
         [514, 556]],

        [[242, 300],
         [706, 764]]]])

In [ ]:
print(np.dot(d[0],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[0],d.reshape(2,4,2)[1]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[0]),"\n")
print(np.dot(d[1],d.reshape(2,4,2)[1]),"\n")

[[ 50  60]
 [114 140]] 

[[130 140]
 [322 348]] 

[[178 220]
 [242 300]] 

[[514 556]
 [706 764]] 



*   Matmul hace las multiplicaciones matriz a matriz (matrices como elementos)
*   dot toma los números dentro de las matrices como elementos. 



In [ ]:
np.matmul(d,d.reshape(2,4,2))

array([[[ 50,  60],
        [114, 140]],

       [[514, 556],
        [706, 764]]])

#### Máximo, mínimo, aleatorio

In [ ]:
print("d =\n",d,"\n") #2,2,4
print("max_1=",d.max(axis=1),"\n")
print("max_0=",d.max(axis=0),"\n")

d =
 [[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]] 

max= [[ 5  6  7  8]
 [13 14 15 16]] 

max= [[ 9 10 11 12]
 [13 14 15 16]] 

